# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Kindraywind
tagline:          My very own website.
url:              Kindraywind.github.io
paginate:         3
baseurl:          /
author:
  name:           Woramet Muangsiri
  url:            Kindraywind.github.io
  email:          krw127@hotmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
